### ISSUE TITLE
No service appears after installation of acunetix 13

### ISSUE THREAD

**Issue by 5Laos** [vncloudsco/acunetix#1]
Hello, after I have seen your docker installation, I want to manually install it in debian 9, but when I finished the execution of acunetix_13.0.200217097_x64_.sh, I did not see the service of Acunetix in the file of /etc/init.d, could you please tell me how you did it?Or do you have a record of the installation of Acunetix 13?Looking forward to your reply.

**Comment by vncloudsco** [comment]
Thank man contact me.
Sorry my image was deleted. I've updated you can only pull back. 
As for the software process, when you use the docker you won't see it clearly. moreover this software runs from bash file so you won't be able to find its service.

New hub:

**Comment by enderphan94** [comment]
I've tried to start the service, but it asks for root priv.

I copied the .accunetix file from home to ~root folder. I was able to run the ./start.sh file but it gave me an error of privileges.

How could I start the service? Thanks

**Comment by vncloudsco** [comment]
> I've tried to start the service, but it asks for root priv.
> 
> I copied the .accunetix file from home to ~root folder. I was able to run the ./start.sh file but it gave me an error of privileges.
How are you installing it? are you using docker? This software does not run with just that one file, it is started from the program's start.sh file.

![image](https://user-images.githubusercontent.com/41409442/81394932-f7d9a780-914c-11ea-9b81-a343bd741c60.png)

**Comment by enderphan94** [comment]
> > I've tried to start the service, but it asks for root priv.
> > I copied the .accunetix file from home to ~root folder. I was able to run the ./start.sh file but it gave me an error of privileges.
> 
> How are you installing it? are you using docker? This software does not run with just that one file, it is started from the program's start.sh file.
> 
> ![image](https://user-images.githubusercontent.com/41409442/81394932-f7d9a780-914c-11ea-9b81-a343bd741c60.png)

I'm using docker. Yes, I do have sufficient files as your picture has shown. I tried to run the ./star.sh and got that error.

**Comment by vncloudsco** [comment]
When you run docker run by default the software has launched, try again with the following command:
`root@docker:~# docker run -it -d -p 443:3443 vouu/acu`
You do not need to run this software again after using the docker command.

**Comment by enderphan94** [comment]
> When you run docker run by default the software has launched, try again with the following command:
> `root@docker:~# docker run -it -d -p 443:3443 vouu/acu`
> You do not need to run this software again after using the docker command.

Thanks for the command, it seems to be running without throwing any errors.

I've tried to look up the port to access its web page with `docker ps` but it gives nothing.

I should be able to access the web page at : `localhost:3443`, am I right?

Appreciate your help!

**Comment by enderphan94** [comment]
I got it working, just a port conflict. Thanks!
