### ISSUE TITLE
problem after run

### ISSUE THREAD

**Issue by FuraXx** [vncloudsco/acunetix#2]
hello when i run i have this error
![acu](https://user-images.githubusercontent.com/33160388/79253260-2ed8d800-7e83-11ea-9931-6a1eb5ddee18.png)

**Comment by vncloudsco** [comment]
Let me know what did you do to get such error information?

**Comment by Petagorus** [comment]
i'm have issue after docker pull vouu/acu and run

**Comment by mrsixman** [comment]
i'm have this a issue after docker pull vouu/acu and docker run vouu/acu

**Comment by vncloudsco** [comment]
Thank you for reporting bugs. 
We are check log.
run: `root@docker:~# docker pull vouu/acu`

```
root@docker:~# docker pull vouu/acu
Using default tag: latest
latest: Pulling from vouu/acu
014a6d74f96c: Pull complete
9febb14563a0: Pull complete
c38f04972c6b: Pull complete
9d39d049d5d0: Pull complete
4e80058918bf: Pull complete
ccd85f0810ad: Pull complete
6ab25bddb799: Pull complete
789ba1ebcb41: Pull complete
524584107b55: Pull complete
40a1af1b9680: Pull complete
fb6edc730b9f: Pull complete
270f87c17cf3: Pull complete
8159e4fffac9: Pull complete
01d3dc4e9fe9: Pull complete
a386beee6e20: Pull complete
46fa80bd0f33: Pull complete
2d3ff71a091d: Pull complete
6f41a333af7c: Pull complete
a0f39fb05a72: Pull complete
e14a21a94fd2: Pull complete
598c15f2dbb9: Pull complete
e18d140c41eb: Pull complete
20f18873451d: Pull complete
7f37d15d1b4c: Pull complete
d6bbc900e150: Pull complete
b0a11828cb42: Pull complete
719f9f8ccec7: Pull complete
26b7fd51b6c7: Pull complete
0e0a519db5d6: Pull complete
f25ba348214a: Pull complete
Digest: sha256:f33ef4eafb4e73d55b2b23176a7438dda5f7c9a1e57e417c4b8c67b6383387c9
Status: Downloaded newer image for vouu/acu:latest
docker.io/vouu/acu:latest
```
and run:

```
root@docker:~# docker run -it -d -p 443:3443 vouu/acu
cf59bf69851d1da8864f5db21df0b8b1256c0d95c17ce84ae78fb2eb9a4bd660
```

we didn't see any errors, try running again, thank you

![image](https://user-images.githubusercontent.com/41409442/81463343-302bc500-91e3-11ea-9d3e-b4b385a51dfa.png)

**Comment by htoochonaung** [comment]
i got this problem .
` ✘⚡ root@thaw  /opt/acunetix   master  docker pull vouu/acu
Using default tag: latest
latest: Pulling from vouu/acu
014a6d74f96c: Pull complete 
9febb14563a0: Pull complete 
c38f04972c6b: Pull complete 
9d39d049d5d0: Pull complete 
4e80058918bf: Pull complete 
ccd85f0810ad: Pull complete 
6ab25bddb799: Pull complete 
789ba1ebcb41: Pull complete 
524584107b55: Pull complete 
40a1af1b9680: Extracting [======================================>            ]  60.72MB/79.85MB
fb6edc730b9f: Download complete 
270f87c17cf3: Downloading [=====================>                             ]  34.81MB/81.52MB
8159e4fffac9: Download complete 
01d3dc4e9fe9: Downloading [=====>                                             ]  8.076MB/72.52MB
a386beee6e20: Downloading 
46fa80bd0f33: Waiting 
2d3ff71a091d: Waiting 
6f41a333af7c: Waiting 
a0f39fb05a72: Waiting 
e14a21a94fd2: Waiting 
598c15f2dbb9: Waiting 
e18d140c41eb: Waiting 
20f18873451d: Waiting 
7f37d15d1b4c: Waiting 
d6bbc900e150: Waiting 
b0a11828cb42: Waiting 
719f9f8ccec7: Waiting 
26b7fd51b6c7: Waiting 
0e0a519db5d6: Waiting 
f25ba348214a: Waiting 
unauthorized: authentication required
`

**Comment by vncloudsco** [comment]
@htoochonaung thank you report
I have checked and found no errors, please check again or use docker login, or sudo command.

```
root@vouu:~/elastalert-docker# docker pull vouu/acu
Using default tag: latest
latest: Pulling from vouu/acu
014a6d74f96c: Pull complete
9febb14563a0: Pull complete
c38f04972c6b: Pull complete
9d39d049d5d0: Pull complete
4e80058918bf: Pull complete
ccd85f0810ad: Pull complete
6ab25bddb799: Pull complete
789ba1ebcb41: Pull complete
524584107b55: Pull complete
40a1af1b9680: Pull complete
fb6edc730b9f: Pull complete
270f87c17cf3: Pull complete
8159e4fffac9: Pull complete
01d3dc4e9fe9: Pull complete
a386beee6e20: Pull complete
46fa80bd0f33: Pull complete
2d3ff71a091d: Pull complete
6f41a333af7c: Pull complete
a0f39fb05a72: Pull complete
e14a21a94fd2: Pull complete
598c15f2dbb9: Pull complete
e18d140c41eb: Pull complete
20f18873451d: Pull complete
7f37d15d1b4c: Pull complete
d6bbc900e150: Pull complete
b0a11828cb42: Pull complete
719f9f8ccec7: Pull complete
26b7fd51b6c7: Pull complete
0e0a519db5d6: Pull complete
f25ba348214a: Pull complete
Digest: sha256:f33ef4eafb4e73d55b2b23176a7438dda5f7c9a1e57e417c4b8c67b6383387c9
Status: Downloaded newer image for vouu/acu:latest
docker.io/vouu/acu:latest
root@vouu:~/elastalert-docker# docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
vouu/acu            latest              4135604754b1        3 months ago        3.33GB
root@vouu:~/elastalert-docker#

```
