### ISSUE TITLE
I did not login with credentials

### ISSUE THREAD

**Issue by ismailtasdelen** [vncloudsco/acunetix#4]
I tried username and password but I couldn't login

**Comment by vncloudsco** [comment]
dear: @ismailtasdelen 
What is your error message? If yes please give me information.

Please double check the whitespace while typing and make sure you have declared it correctly.

Email: contact@manhtuong.net

Password: Abcd1234

**Comment by ismailtasdelen** [comment]
I solved the problem, I had a problem with the service

thanks for the return @vncloudsco (;
